apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ceph-csi-rbd
  namespace: argocd
  labels:
    app.kubernetes.io/name: ceph-csi-rbd
    app.kubernetes.io/part-of: platform
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: ceph-csi-rbd

  sources:

    - repoURL: https://ceph.github.io/csi-charts
      chart: ceph-csi-rbd
      targetRevision: 3.10.0 
      helm:
        valueFiles:
          - $values/helm-values/ceph-csi-rbd/values.yaml

    - repoURL: https://github.com/prinnnnnn/capstone-gitops.git
      targetRevision: main
      ref: values

  syncPolicy:
    automated:
      prune: true      
      selfHeal: true     
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true