images:
  tags:
    bootstrap: "quay.io/airshipit/heat:2025.1-ubuntu_noble"
    db_init: "quay.io/airshipit/heat:2025.1-ubuntu_noble"
    db_drop: "quay.io/airshipit/heat:2025.1-ubuntu_noble"
    ks_user: "quay.io/airshipit/heat:2025.1-ubuntu_noble"
    ks_service: "quay.io/airshipit/heat:2025.1-ubuntu_noble"
    ks_endpoints: "quay.io/airshipit/heat:2025.1-ubuntu_noble"
    glance_db_sync: "quay.io/airshipit/glance:2025.1-ubuntu_noble"
    glance_api: "quay.io/airshipit/glance:2025.1-ubuntu_noble"
    glance_metadefs_load: "quay.io/airshipit/glance:2025.1-ubuntu_noble"
    glance_storage_init: "docker.io/openstackhelm/ceph-config-helper:latest-ubuntu_jammy"

storage: pvc
volume:
  class_name: general
  size: 30Gi
  accessModes:
    - ReadWriteOnce

dependencies:
  static:
    api:
      jobs:
        - glance-storage-init
        - glance-db-sync
        - glance-rabbit-init
        - glance-ks-service
        - glance-ks-user
        - glance-ks-endpoints
      services:
        - endpoint: internal
          service: oslo_db
        - endpoint: internal
          service: identity
        - endpoint: internal
          service: oslo_messaging
    ks_user:
      jobs: null
      services:
        - endpoint: internal
          service: identity
    ks_service:
      jobs: null
      services:
        - endpoint: internal
          service: identity