apiVersion: v1
kind: Service
metadata:
  name: argocd-loadbalancer-service
  namespace: argocd                      
  annotations:
    metallb.io/ip-allocated-from-pool: default-ip-pool   
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: argocd-server             
  ports:
    - name: https
      protocol: TCP
      port: 443                           
      targetPort: 8080
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080