apiVersion: v1
kind: Service
metadata:
  name: grafana-loadbalancer-service
  namespace: monitoring                      
  annotations:
    metallb.io/ip-allocated-from-pool: default-ip-pool   
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: grafana                
  ports:
    - name: http
      protocol: TCP
      port: 80                           
      targetPort: 3000