deploymentMode: SingleBinary

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1

singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: ceph-monitoring

  nodeSelector:
    monitoring: enabled

gateway:
  enabled: true
  replicas: 2
  nodeSelector:
    loki-gateway: enabled